---

default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
  - commit-msg
  - post-commit
  - pre-push

default_stages:
  - pre-commit

fail_fast: true

repos:
  - repo: https://gitlab.com/dwp/secure-development/dwp-cli
    rev: v3.18.4
    hooks:
      - id: check-catalog-info
